[build]
  command = "npm run build"     # CRA users: still "npm run build"
  publish = "dist"              # CRA users: "build"

# React Router: send all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"           # keep Node modern & stable
  # Vite only: your hidden admin key
  VITE_ADMIN_KEY = "set-a-long-random-string"
